"""
config.py – Application configuration loaded from environment variables.
All sensitive values should be set via environment variables or a .env file
(never hard-coded in source control).
"""

import os


class Config:
    # ------------------------------------------------------------------ #
    # Flask                                                                #
    # ------------------------------------------------------------------ #
    SECRET_KEY: str = os.environ.get("SECRET_KEY", "change-me-in-production")
    DEBUG: bool = os.environ.get("FLASK_DEBUG", "false").lower() == "true"

    # ------------------------------------------------------------------ #
    # CORS                                                                 #
    # ------------------------------------------------------------------ #
    # Comma-separated list of trusted origins, e.g.:
    #   CORS_ORIGINS="https://app.example.com,https://admin.example.com"
    # Leave empty (default) only for local development; restrict in production.
    CORS_ORIGINS: str = os.environ.get("CORS_ORIGINS", "*")

    # ------------------------------------------------------------------ #
    # JWT                                                                  #
    # ------------------------------------------------------------------ #
    # Seconds until an access token expires (default: 24 hours)
    JWT_EXPIRY_SECONDS: int = int(os.environ.get("JWT_EXPIRY_SECONDS", 86400))

    # ------------------------------------------------------------------ #
    # Firebase                                                             #
    # ------------------------------------------------------------------ #
    # Absolute or relative path to the Firebase service-account JSON file
    FIREBASE_CREDENTIALS_PATH: str = os.environ.get(
        "FIREBASE_CREDENTIALS_PATH", "serviceAccountKey.json"
    )
    FIREBASE_STORAGE_BUCKET: str = os.environ.get("FIREBASE_STORAGE_BUCKET", "")

    # ------------------------------------------------------------------ #
    # Qdrant                                                               #
    # ------------------------------------------------------------------ #
    QDRANT_HOST: str = os.environ.get("QDRANT_HOST", "localhost")
    QDRANT_PORT: int = int(os.environ.get("QDRANT_PORT", 6333))
    QDRANT_COLLECTION: str = os.environ.get(
        "QDRANT_COLLECTION", "discharge_documents"
    )
    # Embedding vector size – must match the model used in rag_service.py
    QDRANT_VECTOR_SIZE: int = int(os.environ.get("QDRANT_VECTOR_SIZE", 384))

    # ------------------------------------------------------------------ #
    # Sentence-Transformers / LLM                                          #
    # ------------------------------------------------------------------ #
    EMBEDDING_MODEL: str = os.environ.get(
        "EMBEDDING_MODEL", "sentence-transformers/all-MiniLM-L6-v2"
    )
    # HuggingFace model used for answer generation
    LLM_MODEL: str = os.environ.get(
        "LLM_MODEL", "google/flan-t5-base"
    )
    # Maximum tokens generated by the LLM
    LLM_MAX_NEW_TOKENS: int = int(os.environ.get("LLM_MAX_NEW_TOKENS", 256))

    # ------------------------------------------------------------------ #
    # RAG chunking                                                         #
    # ------------------------------------------------------------------ #
    RAG_CHUNK_SIZE: int = int(os.environ.get("RAG_CHUNK_SIZE", 400))
    RAG_CHUNK_OVERLAP: int = int(os.environ.get("RAG_CHUNK_OVERLAP", 50))

    # ------------------------------------------------------------------ #
    # Firebase Storage signed-URL expiry                                   #
    # ------------------------------------------------------------------ #
    # Expiry in seconds for signed download URLs (default: 1 hour)
    STORAGE_SIGNED_URL_EXPIRY: int = int(
        os.environ.get("STORAGE_SIGNED_URL_EXPIRY", 3600)
    )
